### ISSUE TITLE
语音消息本地能播放，但是对方点击语音消息报错

### ISSUE THREAD

**Issue by zhoutongbie** [rongcloud/imkit-flutter-quickstart#9]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
flutter 1.12.13+hot8
* 异常设备是 iOS 还是 Android，列出具体机型和系统
iOS

语音消息本地能播放 但是对方点击语音消息报错了 错误如下
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Audio Player, player is not set, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      FlutterSound.stopPlayer (package:flutter_sound/flutter_sound.dart:410:36)
#3      MediaUtil.stopPlayAudio (package:flutterappylx/packages/rong_im/im/util/media_util.dart:142:18)
#4      MediaUtil.startPlayAudio (package:flutterappylx/packages/rong_im/im/util/media_util.dart:135:7)
#5      _ConversationPageState.didTapMessageItem (package:flutterappylx/packages/rong_im/im/pages/conversation_page.dart:562:28)
#6      _MessageContentListState.didTapMessageItem (package:flutterappylx/packages/rong_im/im/pages/item/message_content_list.dart:146:14)
#7      _ConversationItemState.__onTapedMesssage (package:flutterappylx/packages/rong_im/im/pages/item/conversation_item.dar<…>
flutter: startPlayer result: http://rongcloud-audio.ronghub.com/audio_amr__RC-2020-05-03_6633_1588483001814.aac?e=1604035002&token=livk5rb3__JZjCtEiMxXpQ8QscLxbNLehwhHySnX:XX4OBmpSwXfNSxjAZDytBuvkrbI=

**Comment by CNHarrySun** [comment]
您换一个播放库试下，建议您将高清语音消息下载到本地后，根据本地地址播放。
